// <auto-generated />
namespace GreenThumb.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class datatableoverhall : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datatableoverhall));
        
        string IMigrationMetadata.Id
        {
            get { return "202202121937436_data table overhall"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
