// <auto-generated />
namespace GreenThumb.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Byteupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Byteupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202202161325150_Byte[]update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
